# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B3IO6yKuRKAywUYOwamptSoIFSwy5WDG
"""

import matplotlib.pyplot as plt
import numpy as np

def main():
    x_i = 50
    iterations = 15

    x_vals = []
    err_vals = []

    for i in range(iterations):
        f_x_i = x_i * x_i * x_i - x_i - 1
        d_f_x_i = 3 * x_i * x_i - 1
        x_i1 = x_i - f_x_i / d_f_x_i
        err = x_i - x_i1
        re = err / x_i1

        x_vals.append(i)
        err_vals.append(err)

        print(f"i = {i}")
        print(f"xi = {x_i:.5f}")
        print(f"f(xi) = {f_x_i:.5f}")
        print(f"f'(xi) = {d_f_x_i:.5f}")
        print(f"xi+1 = {x_i1:.5f}")
        print(f"approx. error = {err:.5f}")
        print(f"rel. approx. error = {re:.5f}\n")

        x_i = x_i1

    plot_data(x_vals, err_vals)

def plot_data(x_vals, y_vals):
    plt.bar(x_vals, y_vals)
    plt.xlabel('Iteration No.')
    plt.ylabel('Error')
    plt.title('Approximation Error vs. Iteration')
    plt.show()

if __name__ == "__main__":
    main()